---
hide:
  - navigation
  - toc
---

# Buy

Get your Jetson developer kit to try generative AIs in your own local environment.

!!! note

    The availablility and the price of Jetson developer kits vary depending on your region.<br>Please click "Jetson Store" button to find out the availability on the page next.


| | Product | Action |
|-|-|-|
| <img src="./images/jetson-agx-orin-dev-kit-3qtr-front-right-reverse_800px.png" width="200" style="margin-top: 2em"> | <div style="font-size: 1.3em; font-weight: 800">Jetson AGX Orin 64GB Developer Kit</div><div _ngcontent-eut-c10="" class="specs-container 479"><ul _ngcontent-eut-c10=""><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">AI Perf: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">275 TOPS</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">GPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">NVIDIA Ampere architecture with 2048 NVIDIA CUDA cores and 64 tensor cores</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">CPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">12-core Arm Cortex-A78AE v8.2 64-bit CPU 3MB L2 + 6MB L3</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Memory: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">64GB 256-bit LPDDR5 &#124; 204.8 GB/s</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Storage: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">64GB eMMC 5.1</span></div><!----></li><!----></ul><div _ngcontent-eut-c10="" style="display: flex; justify-content: space-between;"><!----><!----></div></div> | <a href="https://store.nvidia.com/jetson/store/" title="Go to Jetson Store" class="nv-buy-link"> Jetson Store </a> |
| <img src="./images/jetson-agx-orin-dev-kit-3qtr-front-right-reverse_800px.png" width="200" style="margin-top: 2em"> | <div style="font-size: 1.3em; font-weight: 800">Jetson AGX Orin Developer Kit</div><div _ngcontent-eut-c10="" class="specs-container 479"><ul _ngcontent-eut-c10=""><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">AI Perf: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">275 TOPS</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">GPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">NVIDIA Ampere architecture with 2048 NVIDIA CUDA cores and 64 tensor cores</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">CPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">12-core Arm Cortex-A78AE v8.2 64-bit CPU 3MB L2 + 6MB L3</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Memory: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">32GB 256-bit LPDDR5 &#124; 204.8 GB/s</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Storage: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">64GB eMMC 5.1</span></div><!----></li><!----></ul><div _ngcontent-eut-c10="" style="display: flex; justify-content: space-between;"><!----><!----></div></div> | <a href="https://store.nvidia.com/jetson/store/" title="Go to Jetson Store" class="nv-buy-link"> Jetson Store </a> |
| <img src="./images/NVIDIA-JetsonOrin-3QTR-Front-Left_800px.png" width="200" style="margin-top: 3em"> | <div style="font-size: 1.3em; font-weight: 800">Jetson Orin Nano Developer Kit</div><div _ngcontent-eut-c10="" class="specs-container 479"><ul _ngcontent-eut-c10=""><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">AI Perf: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">40 TOPS</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">GPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">1024-core NVIDIA Ampere architecture GPU with 32 Tensor Cores</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">CPU: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">6-core Arm® Cortex®-A78AE v8.2 64-bit CPU 1.5MB L2 + 4MB L3</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Memory: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">8GB 128-bit LPDDR5  68 GB/s</span></div><!----></li><li _ngcontent-eut-c10=""><div _ngcontent-eut-c10="" kuitext="" class="specs 482 p-medium c-fOVUQc" data-testid="kui-text">Storage: <span _ngcontent-eut-c10="" kuitext="" data-testid="kui-text" class="c-fOVUQc">SD Card Slot &amp; external NVMe via M.2 Key M</span></div><!----></li><!----></ul><div _ngcontent-eut-c10="" style="display: flex; justify-content: space-between;"><!----><!----></div></div> | <a href="https://store.nvidia.com/jetson/store/" title="Go to Jetson Store" class="nv-buy-link"> Jetson Store </a> |

